Repository K-u-r-c/RatChat, pull requests merged in 2025-10, with the labels that each got.

#134 Naxden/issue133
  client/src/app/shared/components/ConfirmDialog.tsx
  client/src/features/chatRooms/ChatRoomSidebarContent.tsx
  client/src/features/chatRooms/details/ChatRoomMemberActions.tsx
  client/src/features/chatRooms/details/ChatRoomMemberPopover.tsx
  client/src/features/chatRooms/settings/ChatRoomSettingsBans.tsx
  client/src/features/friends/Friends.tsx
Labels: enhancement, help wanted

#137 Production
  .github/workflows/main_ratchat.yml
  Application/Friends/Queries/GetFriends.cs
  Application/Interfaces/IUserStatusService.cs
  Infrastructure/Services/UserStatusService.cs
  client/vite.config.ts
Labels: bug, help wanted

#146 Custom logging for clients SignalR hubs
  client/src/lib/hooks/useChatRoomModerationEventsRealtime.ts
  client/src/lib/hooks/useChatRoomRolesRealtime.ts
  client/src/lib/hooks/useChatRoomsProfileImageRealtime.ts
  client/src/lib/hooks/useDirectMessages.ts
  client/src/lib/hooks/useEncryptedDirectMessages.ts
  client/src/lib/hooks/useFriendsRealtime.ts
  client/src/lib/hooks/useStatusRealtime.ts
  client/src/lib/realtime/encryptedMessagesHub.ts
  client/src/lib/realtime/messagesHub.ts
  client/src/lib/realtime/voiceHub.ts
  client/src/lib/util/hubLogger.ts
Labels: enhancement

#148 Fix for share settings
  client/src/app/shared/components/ScreenShareSettingsDialog.tsx
Labels: bug, help wanted

#154 Ensuring before assigning a role to user
  Application/Development/DbInitializer.cs
  Infrastructure/Services/ChatRoomRoleService.cs
Labels: bug, help wanted

#156 Fix message reply
  client/src/app/shared/components/mediaChatComponent/chatMessageList/ChatMessageList.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/ReplyPreview.tsx
Labels: bug, help wanted

#157 Rat chat 151
  API/Controllers/FriendsController.cs
  API/Services/ChatAppearanceNotificationService.cs
  API/Services/ChatRoomsNotificationService.cs
  API/Services/DirectMessagesNotificationService.cs
  API/SignalR/ChatRoomRolesHub.cs
  Application/ChatChannels/Commands/UpdateChatChannel.cs
  Application/ChatRoomRoles/Commands/DeleteChatRoomRole.cs
  Application/ChatRoomRoles/Commands/SetMemberDisplayRole.cs
  Application/ChatRoomRoles/Commands/UnassignChatRoomRole.cs
  Application/ChatRoomRoles/DTOs/ReorderChatRoomRolesDto.cs
  Application/ChatRoomRoles/Queries/GetChatRoomRoles.cs
  Application/ChatRoomRoles/Queries/GetUserChatRoomRoles.cs
  Application/ChatRooms/Commands/UpdateChatRoomImage.cs
  Application/Profiles/Commands/UpdateProfile.cs
  Infrastructure/Security/UserAccessor.cs
  Infrastructure/Services/RolePermissionService.cs
  Infrastructure/Storage/AzureBlobStorage.cs
  client/package.json
  client/src/app/layout/App.tsx
  client/src/app/layout/AuthLayout.tsx
  client/src/app/layout/DesktopDownloadBanner.tsx
  client/src/app/layout/desktopDownloadPromo.ts
  client/src/app/router/Routes.tsx
  client/src/features/download/DownloadPage.tsx
Labels: enhancement, devops
