Repository K-u-r-c/RatChat, pull requests merged in 2025-09, with the labels that each got.

#57 Add proper README.md file to the project and repository
  README.md
Labels: documentation, help wanted

#64 PR add option to send multiple media files at once
  client/src/app/shared/components/mediaChatComponent/ChatInput.tsx
  client/src/app/shared/components/mediaChatComponent/ChatMessageList.tsx
  client/src/app/shared/components/mediaChatComponent/GroupedMediaMessage.tsx
  client/src/app/shared/components/mediaChatComponent/MediaChatComponent.tsx
  client/src/app/shared/components/mediaChatComponent/MultiFilePreview.tsx
  client/src/lib/hooks/useFileUpload.ts
Labels: enhancement

#62 feat: Implement chat room access control with permissions and error handling
  API/Controllers/ChatRoomsController.cs
  API/SignalR/MessageHub.cs
  Application/Messages/Commands/AddMessage.cs
  Domain/Enums/ChatRoomPermissions.cs
  Domain/Enums/ChatRoomRoles.cs
  Infrastructure/Services/RolePermissionService.cs
  client/src/lib/api/agent.ts
  client/src/lib/hooks/useChatRooms.ts
  client/src/lib/hooks/useMessages.ts
  client/src/lib/stores/uiStore.ts
  client/src/lib/types/chatroomPermissions.ts
Labels: bug, help wanted

#65 feat: add message and direct message reactions functionality
  API/SignalR/DirectMessageHub.cs
  API/SignalR/MessageHub.cs
  Application/Core/MappingProfiles.cs
  Application/DirectMessages/Commands/ToggleDirectMessageReaction.cs
  Application/DirectMessages/DTOs/DirectMessageDto.cs
  Application/DirectMessages/Queries/GetDirectMessages.cs
  Application/Messages/Commands/ToggleMessageReaction.cs
  Application/Messages/DTOs/MessageDto.cs
  Application/Messages/DTOs/MessageReactionDto.cs
  Application/Messages/DTOs/ReactionUpdateDto.cs
  Application/Messages/Queries/GetMessages.cs
  Domain/DirectMessage.cs
  Domain/DirectMessageReaction.cs
  Domain/Message.cs
  Domain/MessageReaction.cs
  Persistance/AppDbContext.cs
  Persistance/Migrations/20250617233414_InitialMigrationWithMediaFilesSupportForChats.Designer.cs
  Persistance/Migrations/20250620104628_AddedUserStatusTracking.cs
  Persistance/Migrations/20250620175857_DeleteCustomStatusMessage.Designer.cs
  Persistance/Migrations/20250620175857_DeleteCustomStatusMessage.cs
  Persistance/Migrations/20250630095821_RemoveIsReadFromDirectMessages.Designer.cs
  Persistance/Migrations/20250630095821_RemoveIsReadFromDirectMessages.cs
  Persistance/Migrations/20250630120636_AddDefaultEmoji.Designer.cs
  Persistance/Migrations/20250630120636_AddDefaultEmoji.cs
  Persistance/Migrations/20250904064722_AddMessageReplies.Designer.cs
  Persistance/Migrations/20250904064722_AddMessageReplies.cs
  Persistance/Migrations/20250904110151_ChatRoomRolesAdded.Designer.cs
  Persistance/Migrations/20250904110151_ChatRoomRolesAdded.cs
  Persistance/Migrations/20250905112427_AddChatRoomInvites.Designer.cs
  Persistance/Migrations/20250905112427_AddChatRoomInvites.cs
  Persistance/Migrations/20250906171749_InitialMigration.Designer.cs
  Persistance/Migrations/20250906171749_InitialMigration.cs
  Persistance/Migrations/AppDbContextModelSnapshot.cs
  client/src/app/shared/components/EmojiPicker.tsx
  client/src/app/shared/components/mediaChatComponent/ChatInput.tsx
  client/src/app/shared/components/mediaChatComponent/ChatMessageList.tsx
  client/src/app/shared/components/mediaChatComponent/MediaChatComponent.tsx
  client/src/app/shared/components/mediaChatComponent/MessageReactions.tsx
  client/src/lib/hooks/useDirectMessages.ts
  client/src/lib/hooks/useMessages.ts
  client/src/lib/types/index.d.ts
Labels: enhancement, help wanted

#83 K u r c/issue82
  .github/copilot-instructions.md
  client/src/app/layout/App.tsx
  client/src/app/layout/SideNav/SideNav.tsx
  client/src/app/layout/styles.css
  client/src/app/shared/components/EmojiPicker.tsx
  client/src/app/shared/components/MessageAvatar.tsx
  client/src/app/shared/components/MessageAvatarWithStatus.tsx
  client/src/app/shared/components/mediaChatComponent/ChatAvatar.tsx
  client/src/app/shared/components/mediaChatComponent/ChatHeader.tsx
  client/src/app/shared/components/mediaChatComponent/ChatInput.tsx
  client/src/app/shared/components/mediaChatComponent/ChatMessageList.tsx
  client/src/app/shared/components/mediaChatComponent/DragOverlay.tsx
  client/src/app/shared/components/mediaChatComponent/MediaChatComponent.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/ChatMessageList.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/DateDivider.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/GroupedMediaRow.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/MessageBubble.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/MessageHeader.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/ReplyPreview.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/SideActions.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/SingleMessageRow.tsx
  client/src/app/shared/components/mediaChatComponent/chatMessageList/buildRenderItems.ts
  client/src/app/theme.ts
  client/src/features/directChats/DirectChatDetails.tsx
  client/src/features/directChats/DirectSearchInput.tsx
  client/src/lib/hooks/useMessages.ts
  client/src/lib/hooks/useScrollHandler.ts
Labels: enhancement

#88 Fix bug with changing chat rooms
  API/Program.cs
  client/src/lib/hooks/useMessages.ts
Labels: bug

#96 Fix redirection to login page
  client/src/app/layout/styles.css
  client/src/app/router/Routes.tsx
  client/src/features/errors/NotFound.tsx
  client/src/features/errors/ServerError.tsx
Labels: bug, help wanted

#99 Fix media images get from backend to frontend on production
  API/Controllers/MediaController.cs
Labels: bug, help wanted

#101 Create nice emails that are being sent
  Infrastructure/Email/EmailSender.cs
Labels: enhancement, help wanted

#103 feat: implement message encryption at rest using AES-256-GCM
  API/Program.cs
  API/appsettings.Development.json
  Persistance/AppDbContext.cs
  Persistance/Security/EncryptedStringConverter.cs
  Persistance/Security/MessageCrypto.cs
  README.md
  client/src/app/layout/SideNav/DefaultSidebarContent.tsx
  client/src/app/layout/SideNav/SideNav.tsx
  client/src/app/shared/components/mediaChatComponent/ChatInput.tsx
  client/src/app/shared/components/mediaChatComponent/MediaChatComponent.tsx
  client/src/features/directChats/DirectChatDetails.tsx
  client/src/features/friends/Friends.tsx
Labels: enhancement, help wanted

#124 Add discord like actions ribbon that allows user to handle microphone…
  client/src/app/layout/SideNav/SecondarySidebar.tsx
  client/src/app/layout/SideNav/SideNav.tsx
  client/src/app/layout/UserActionRibbon.tsx
  client/src/app/layout/UserMenuIcon.tsx
  client/src/app/shared/components/VoiceAudioLayer.tsx
  client/src/app/shared/components/mediaChatComponent/ChatInput.tsx
  client/src/app/shared/components/mediaChatComponent/MediaChatComponent.tsx
  client/src/features/chatRooms/ChatRoomSidebarContent.tsx
  client/src/lib/hooks/useVoiceChannel.ts
  client/src/lib/types/voiceChannel.ts
Labels: enhancement

#131 Naxden/issue76
  API/Controllers/ChatRoomsController.cs
  API/SignalR/ChatRoomRolesHub.cs
  Application/Interfaces/IRolePermissionService.cs
  Domain/Enums/ChatRoomPermissions.cs
  Domain/Enums/ChatRoomRoles.cs
  client/src/app/shared/components/ChatRoomPermissionItem.tsx
  client/src/app/shared/components/ChatRoomRoleButton.tsx
  client/src/app/shared/components/mediaChatComponent/MediaChatComponent.tsx
  client/src/features/chatRooms/ChatRoomImageUpload.tsx
  client/src/features/chatRooms/ChatRoomSidebarContent.tsx
  client/src/features/chatRooms/details/ChatRoomDetails.tsx
  client/src/features/chatRooms/details/ChatRoomDetailsChat.tsx
  client/src/features/chatRooms/details/ChatRoomMemberActions.tsx
  client/src/features/chatRooms/details/ChatRoomMemberDialog.tsx
  client/src/features/chatRooms/details/ChatRoomMemberPopover.tsx
  client/src/features/chatRooms/details/ChatRoomMembersBar.tsx
  client/src/features/chatRooms/details/ChatRoomRolesBar.tsx
  client/src/features/chatRooms/forms/ChatRoomManageRolesForm.tsx
  client/src/features/chatRooms/forms/ChatRoomRoleUpdateForm.tsx
  client/src/features/chatRooms/settings/ChatRoomSettingsBans.tsx
  client/src/features/chatRooms/settings/ChatRoomSettingsRoles.tsx
  client/src/features/directChats/DirectChatDetails.tsx
  client/src/lib/hooks/useChatRoomModerationEventsRealtime.ts
  client/src/lib/hooks/useChatRoomRoles.ts
  client/src/lib/hooks/useChatRoomRolesRealtime.ts
  client/src/lib/schemas/chatRoomRoleSchema.ts
  client/src/lib/types/chatroomPermissions.ts
  client/src/lib/types/index.d.ts
Labels: help wanted
